services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 8094:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aby
      - MONGO_INITDB_ROOT_PASSWORD=aby
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aby
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aby
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}